// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1gJHMxfsp0iQY7IdNsCJmVGm4Ze42aCg',
    appId: '1:1076087169316:web:b196f846c5022b9b1e53b1',
    messagingSenderId: '1076087169316',
    projectId: 'campus-hub-af105',
    authDomain: 'campus-hub-af105.firebaseapp.com',
    storageBucket: 'campus-hub-af105.firebasestorage.app',
    measurementId: 'G-3T9V3DT3VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5InqARuZgM__MfHL4Hgy2dVXyuqzw1gM',
    appId: '1:1076087169316:android:af9c4910e8a60af01e53b1',
    messagingSenderId: '1076087169316',
    projectId: 'campus-hub-af105',
    storageBucket: 'campus-hub-af105.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATvK8ldPe9I79WtFHeSpdile3dYBhQNis',
    appId: '1:1076087169316:ios:e9724c24bbc083c21e53b1',
    messagingSenderId: '1076087169316',
    projectId: 'campus-hub-af105',
    storageBucket: 'campus-hub-af105.firebasestorage.app',
    iosClientId: '1076087169316-avkl3ogu38ajen156oq8n5t9jmrvhsor.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATvK8ldPe9I79WtFHeSpdile3dYBhQNis',
    appId: '1:1076087169316:ios:e9724c24bbc083c21e53b1',
    messagingSenderId: '1076087169316',
    projectId: 'campus-hub-af105',
    storageBucket: 'campus-hub-af105.firebasestorage.app',
    iosClientId: '1076087169316-avkl3ogu38ajen156oq8n5t9jmrvhsor.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1gJHMxfsp0iQY7IdNsCJmVGm4Ze42aCg',
    appId: '1:1076087169316:web:1fa043c632bf9c891e53b1',
    messagingSenderId: '1076087169316',
    projectId: 'campus-hub-af105',
    authDomain: 'campus-hub-af105.firebaseapp.com',
    storageBucket: 'campus-hub-af105.firebasestorage.app',
    measurementId: 'G-VKC741XQ5P',
  );
}